@startuml

package "library" #DDDDDD {

	object BookManager {
    		 username = "liyue"
    		 password = "liyue123"
    }



	object reader {
    	 	username = "liyue"
    		password = "liyue123
    	}


	object book {
    	 	书名 = "Python与机器学习实战"
    	 	ISBN号 = "156-211-003-231"
    	 	总量 = "30"
    	 	库存 = "25"
    	 	价格 = "69"
    	 	出版社 = "电子工业出版社"
    	 	简介 = "决策树，继集成学习，支持向量机"
    	 	作者 = "何宇健"
    	}

	object order {
    	 	读者姓名 = "李玥"
    	 	图书ISBN号 = "11-33-55"
    	 	借出时间 = "2017-5-3"
    	 	归还期限 = "2018-6-10"
    }
    object return {
            读者姓名 = "李玥"
            图书ISBN号 = "22-32-19"
            还书日期 = "2018-4-3"


    }

	note "<color:blue>省略Getter和Setter方法。</color>" as note1

	book .. note1
	note1 .. 借书记录


	BookManager <|-- return: 管理信息
	reader "1" *-- "N" order : 借书和还书
	return "1" *-- "N" order : 还书
	order "1" o-- "1" book : 一一对应
	借书记录 "N" -- "1"  数据库: 登记和归还
	BookManager "N" -- "N" book : 维护图书
	BookManager "N" -- "N" reader : 维护读者信息


}


@enduml